#!/usr/bin/env python3
import sys
from math import isqrt

def factorize_number(n):
    """Factorize a number"""
    for i in range(2, isqrt(n) + 1):
        if n % i == 0:
            return f"{n}={n // i}*{i}"
    return f"{n} is prime or invalid"

def factorize_list(numbers):
    """Factorize each number in the list"""
    for num in numbers:
        print(factorize_number(num))

if len(sys.argv) == 2:
    with open(sys.argv[1], "r") as file:
        numbers = [int(line.strip()) for line in file.readlines()]
        factorize_list(numbers)
